# Generated by Django 4.0 on 2022-01-18 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_shop',
            name='created_by',
        ),
    ]
