# Generated by Django 4.0 on 2021-12-31 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_shop', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='bookshop',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='book_shop.book_shop'),
        ),
        migrations.AddField(
            model_name='books',
            name='created_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
