# Generated by Django 4.0 on 2022-01-01 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='created_by',
        ),
    ]
