# Generated by Django 4.0 on 2022-02-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_books_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/book/dist/img'),
        ),
    ]
